parameters:
    adibox_cachebundle.twigextension.cachehelper.class: Adibox\Bundle\CacheBundle\TwigExtension\CacheHelper

services:
     adibox_cachebundle.twigextension.cachehelper:
         class: %adibox_cachebundle.twigextension.cachehelper.class%
         calls:
             - [setContainer, ["@service_container"]]
         tags:
             - { name: twig.extension }

     adibox_cachebundle.kernelevent.listener:
         class: Adibox\Bundle\CacheBundle\EventListener\listener
         arguments: [@service_container]
         tags:
             - { name: kernel.event_listener, event: kernel.view, method: onKernelView, priority: 110 }