parameters:
    adibox_cachebundle.twigextension.cachehelper.class: Adibox\Bundle\CacheBundle\TwigExtension\CacheHelper

services:
     adibox_cachebundle.twigextension.cachehelper:
         class: %adibox_cachebundle.twigextension.cachehelper.class%
         calls:
             - [setContainer, ["@service_container"]]
         tags:
             - { name: twig.extension }