parameters:
#    adibox_cache.example.class: Adibox\Bundle\CacheBundle\Example

services:
#    adibox_cache.example:
#        class: %adibox_cache.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
